import type { IdentityRepository, PasswordHasher, SessionRecord, TokenGenerator, UserRecord, WorkspaceRecord, WorkspaceRepository } from "../ports/identity";
export class AuthorizationError extends Error { constructor(message="unauthorized") { super(message); } }
export class IdentityService {
 constructor(private readonly identities:IdentityRepository, private readonly workspaces:WorkspaceRepository, private readonly passwords:PasswordHasher, private readonly tokens:TokenGenerator, private readonly now:()=>Date) {}
 async register(input:{email:string;displayName:string;password:string}) { const email=input.email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email) || input.password.length<12) throw new Error("invalid_registration"); if (await this.identities.findUserByEmail(email)) throw new Error("email_already_registered"); const createdAt=this.now(); const user:UserRecord={id:this.tokens.id(),email,displayName:input.displayName.trim(),passwordHash:await this.passwords.hash(input.password),status:"active",createdAt}; await this.identities.createUser(user); const workspace=await this.ensurePersonalWorkspace(user); return {user,workspace}; }
 async login(input:{email:string;password:string}) { const user=await this.identities.findUserByEmail(input.email.trim().toLowerCase()); if (!user || user.status!=="active" || !(await this.passwords.verify(input.password,user.passwordHash))) throw new AuthorizationError("invalid_credentials"); const token=this.tokens.opaqueToken(); const session:SessionRecord={id:this.tokens.id(),userId:user.id,tokenDigest:this.tokens.digest(token),expiresAt:new Date(this.now().getTime()+1000*60*60*24*7),revokedAt:null}; await this.identities.createSession(session); const workspace=await this.ensurePersonalWorkspace(user); return {token,user,workspace,session}; }
 async authenticate(token:string) { const session=await this.identities.findSessionByDigest(this.tokens.digest(token)); if (!session || session.revokedAt || session.expiresAt<=this.now()) throw new AuthorizationError(); return session; }
 async logout(token:string) { const session=await this.authenticate(token); await this.identities.revokeSession(session.id,this.now()); }
 async assertWorkspaceAccess(userId:string,workspaceId:string) { const membership=await this.workspaces.findActiveMembership(workspaceId,userId); if (!membership) throw new AuthorizationError("workspace_forbidden"); return membership; }
 private async ensurePersonalWorkspace(user:UserRecord) { const existing=await this.workspaces.findPersonalWorkspace(user.id); if (existing) return existing; const workspace:WorkspaceRecord={id:this.tokens.id(),ownerId:user.id,name:`${user.displayName} personal workspace`,visibility:"private",status:"active",createdAt:this.now()}; await this.workspaces.createWorkspace(workspace); await this.workspaces.createMembership({id:this.tokens.id(),workspaceId:workspace.id,userId:user.id,role:"owner",status:"active"}); return workspace; }
}
