#!/usr/bin/env tsx
/**
 * Codegen: YAML schemas → TypeScript types + Zod schemas
 * Reads core/primitives/*.schema.yaml (id, version, fields, lifecycle, validity_rules)
 * Generates services/mcp-server/src/generated/types.ts and schemas.ts
 * Also root src/generated if needed — but per spec commit generated files.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(moduleDir, "..");
const primitivesDir = path.join(rootDir, "core/primitives");
const outDir = path.join(rootDir, "services/mcp-server/src/generated");

type Field = {
  name: string;
  type: string;
  required?: boolean;
  allowed_values?: string[];
  range?: [number, number];
  minLength?: number;
  maxLength?: number;
};

type Schema = {
  id: string;
  version: string;
  fields: Field[];
  lifecycle: string[];
  validity_rules: string[];
};

function primitiveToPascal(id: string): string {
  // primitive.playbook → Playbook, primitive.data-model → DataModel
  const raw = id.replace(/^primitive\./, "");
  return raw
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function fieldToTsType(f: Field): string {
  let base: string;
  switch (f.type) {
    case "string":
    case "datetime":
      base = "string";
      break;
    case "number":
      base = "number";
      break;
    case "array":
      base = "unknown[]";
      break;
    case "object":
      base = "Record<string, unknown>";
      break;
    case "enum":
      if (f.allowed_values && f.allowed_values.length) {
        base = f.allowed_values.map((v) => `"${v}"`).join(" | ");
      } else base = "string";
      break;
    default:
      base = "unknown";
  }
  return f.required === false ? `${base} | null | undefined` : base;
}

function fieldToZod(f: Field): string {
  let z: string;
  switch (f.type) {
    case "string":
      z = "z.string()";
      if (f.minLength) z += `.min(${f.minLength})`;
      if (f.maxLength) z += `.max(${f.maxLength})`;
      break;
    case "datetime":
      z = "z.string().datetime({ offset: true })";
      break;
    case "number":
      z = "z.number()";
      if (f.range) z += `.min(${f.range[0]}).max(${f.range[1]})`;
      break;
    case "array":
      z = "z.array(z.unknown())";
      break;
    case "object":
      z = "z.record(z.unknown())";
      break;
    case "enum":
      if (f.allowed_values && f.allowed_values.length) {
        const vals = f.allowed_values.map((v) => `"${v}"`).join(", ");
        z = `z.enum([${vals}])`;
      } else z = "z.string()";
      break;
    default:
      z = "z.unknown()";
  }
  if (f.required === false) z += ".optional().nullable()";
  return z;
}

function loadSchemas(): Schema[] {
  const files = fs.readdirSync(primitivesDir).filter((f) => f.endsWith(".schema.yaml"));
  const schemas: Schema[] = [];
  for (const file of files) {
    const raw = fs.readFileSync(path.join(primitivesDir, file), "utf8");
    const parsed = parse(raw) as Schema;
    if (!parsed.id || !parsed.version || !parsed.fields) {
      throw new Error(`Invalid schema ${file}: missing id/version/fields`);
    }
    schemas.push(parsed);
  }
  schemas.sort((a, b) => a.id.localeCompare(b.id));
  return schemas;
}

function generateTypes(schemas: Schema[]): string {
  const header = `// Auto-generated by scripts/gen-schemas.ts — DO NOT EDIT
// Source: core/primitives/*.schema.yaml
// Kernel: ${fs.readFileSync(path.join(rootDir, "core/VERSION"), "utf8").trim()}

`;
  let out = header;
  for (const s of schemas) {
    const name = primitiveToPascal(s.id);
    out += `export interface ${name} {\n`;
    for (const f of s.fields) {
      const opt = f.required === false ? "?" : "";
      out += `  ${f.name}${opt}: ${fieldToTsType(f)};\n`;
    }
    out += `}\n\n`;
    out += `export const ${name}Lifecycle = [${s.lifecycle.map((v) => `"${v}"`).join(", ")}] as const;\n`;
    if (s.validity_rules.length) {
      out += `export const ${name}ValidityRules = [${s.validity_rules.map((v) => `"${v.replace(/"/g, '\\"')}"`).join(", ")}] as const;\n`;
    }
    out += `\n`;
  }
  return out;
}

function generateSchemas(schemas: Schema[]): string {
  const header = `// Auto-generated by scripts/gen-schemas.ts — DO NOT EDIT
import { z } from "zod";

`;
  let out = header;
  for (const s of schemas) {
    const name = primitiveToPascal(s.id);
    out += `export const ${name}Schema = z.object({\n`;
    for (const f of s.fields) {
      out += `  ${f.name}: ${fieldToZod(f)},\n`;
    }
    out += `});\n`;
    out += `export type ${name}Type = z.infer<typeof ${name}Schema>;\n\n`;
  }
  return out;
}

function main() {
  const schemas = loadSchemas();
  console.log(`[gen-schemas] loaded ${schemas.length} schemas: ${schemas.map((s) => s.id).join(", ")}`);
  const types = generateTypes(schemas);
  const zod = generateSchemas(schemas);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "types.ts"), types, "utf8");
  fs.writeFileSync(path.join(outDir, "schemas.ts"), zod, "utf8");
  console.log(`[gen-schemas] wrote ${path.join(outDir, "types.ts")}`);
  console.log(`[gen-schemas] wrote ${path.join(outDir, "schemas.ts")}`);
  // Also mirror to src/generated for strangler fallback (optional)
  const altOut = path.join(rootDir, "src/generated");
  fs.mkdirSync(altOut, { recursive: true });
  fs.writeFileSync(path.join(altOut, "types.ts"), types, "utf8");
  fs.writeFileSync(path.join(altOut, "schemas.ts"), zod, "utf8");
  console.log(`[gen-schemas] mirrored to ${altOut}`);
}

main();
