import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const envPath = path.join(process.cwd(), '.env.local');
const providers = ['Not now — local safe mode', 'Keycloak', 'Authentik', 'Cloudflare Access', 'Custom trusted identity proxy'];

function template(provider: string) {
  return `# CasioPlus local setup — generated by npm run setup:casio
# This file contains NO credentials and is gitignored.
# Add real secrets only in your production secret manager.

# Local development is safe by default: no network SSO is enabled.
CASIO_ACTOR_ROLE=viewer

# Selected SSO integration (not active until CASIO_SSO_SHARED_SECRET is set)
CASIO_SSO_PROVIDER=${provider}
CASIO_SSO_SHARED_SECRET=

# Local stores (all gitignored)
CASIO_METRIC_STORE=data/casio-metric.json
CASIO_COACHING_STORE=data/coaching-sessions.json
CASIO_AUTOMATION_STORE=data/automation-specs.json
CASIO_AUTOMATION_RUN_STORE=data/automation-runs.json
`;
}

async function main() {
  if (!input.isTTY || !output.isTTY) {
    console.log('CasioPlus setup skipped: non-interactive environment. Run `npm run setup:casio` in a terminal.');
    return;
  }
  if (fs.existsSync(envPath)) {
    console.log('.env.local already exists. Nothing was changed. Review it manually if you want to change SSO mode.');
    return;
  }

  const rl = createInterface({ input, output });
  console.log('\nCasioPlus safe setup');
  console.log('This wizard never asks for a password, token or SSO secret.');
  console.log('It makes no network calls and writes only a gitignored .env.local template.\n');
  providers.forEach((provider, index) => console.log(`${index + 1}. ${provider}`));
  const answer = await rl.question('\nSelect SSO provider [1]: ');
  const index = Number(answer || '1') - 1;
  const selected = providers[index] ?? providers[0];
  const confirm = await rl.question(`Create safe local configuration for "${selected}"? [Y/n]: `);
  await rl.close();
  if (confirm.trim().toLowerCase() === 'n') {
    console.log('No files were created.');
    return;
  }

  const provider = selected === providers[0] ? 'none' : selected.toLowerCase().replace(/\s+/g, '-');
  fs.writeFileSync(envPath, template(provider), { encoding: 'utf8', mode: 0o600 });
  console.log('\nCreated .env.local with file mode 0600.');
  console.log('SSO remains disabled until a production secret manager provides CASIO_SSO_SHARED_SECRET.');
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
